### ISSUE TITLE
Fecundity and Atresia codes (for SmartDots)

### ISSUE THREAD

**Issue by cmspinto** [ices-eg/DIG#171]
Codes need to be added to Fecundity and Atresia in SmartDots, 
 it is several vocabulary types.

**Comment by cmspinto** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/carlos/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/carlos/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Stage | Description | Scale | Questions
-- | -- | -- | --
YV | YolkVesicle | Atresia |  
YV_YG | YolkVesicle_YolkGranule | Atresia |  
YG | YolkGranule | Atresia |  
Neg_grid | Negative_grid | Atresia |  
Extra | Extra | Atresia |  
YV_P | YolKVesicle_Profile | Atresia |  
YV_YG_P | YolKVesicle_YolkGranule_Profile | Atresia |  
YG_P | YolKGranule_Profile | Atresia |  
Oocyte_stage_1 | Previtellogenic   oocytes | Histological   Screening |  
Oocyte_stage_2 | Early vitellogenic   oocytes <400 um | Histological   Screening |  
Oocyte_stage_3 | Vitellogenic oocytes | Histological   Screening |  
Oocyte_stage_4 | Migratory nucleus   oocytes | Histological   Screening |  
Hydration_state_1 | Early hydration | Histological   Screening | Question suggestion:   Are hydrated oocytes present? Answer: Yes or No
Hydration_state_2 | Advanced hydration | Histological   Screening |  
Hydration_state_3 | Late hydration | Histological   Screening |  
Egg_stage_1 | New eggs present | Histological   Screening | Question suggestion:   Are eggs present? Answer: Yes or No
Egg_stage_2 | Residual eggs present | Histological   Screening |  
  | POFs | Histological   Screening | Question suggestion:   Are POFs present? Answer: Yes or No
  | spent | Histological   Screening | Question suggestion:   Is the ovary spent? Answer: Yes or No
  | massive atresia | Histological   Screening | Question suggestion:   Is massive atresia present? Answer: Yes or No
  | early alpha atresia | Histological   Screening | Question suggestion:   Is Early atresia present? Answer: Yes or No
  | Discarded | Histological   Screening | Question suggestion:   Should the sample be discarded? Answer: Yes or No
POF_stage_1 | Newly formed | POF Staging |  
POF_stage_2 | Folded | POF Staging |  
POF_stage_3 | Vacuolated | POF Staging |  
POF_stage_4 | Compacted | POF Staging |  
POF_stage_5 | Decreased sized | POF Staging |  
POF_stage_6 | Advanced | POF Staging |  
POF_stage_7 | Residual | POF Staging |  



</body>

</html>

**Comment by cekv** [comment]
Two codetypes for - one for Atresia scale/type and one for the Stages.
No underscore and better description. Codes will be invisible so Carlos can do the tests.

**Comment by pcrjoana** [comment]
Codes implemented, but kept invisible while waiting for better descriptions.
Joana to contact Martia Korta, Cindy and Anders for better descriptions.

**Comment by pcrjoana** [comment]
POF - post ovulatory folicule

**Comment by cekv** [comment]
@evabrna will find descriptions in SISP -5,  ask Cindy in the upcoming meeting.

**Comment by pcrjoana** [comment]
@evabrna to update the descriptions.

**Comment by evabrna** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/evab/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/evab/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Stage | Description | Detailed description | Scale |  
-- | -- | -- | -- | --
YV | YolkVesicle | Number of Yolk Vesical Grid   Points in the entire sample. | Atresia_WGMEGS
YV_YG | YolkVesicle_YolkGranule | Number of Yolk Vesical-Yolk   Granule Grid Points in the entire sample. | Atresia_WGMEGS
YG | YolkGranule | Number of Yolk Granule Grid   Points in the entire sample. | Atresia_WGMEGS
Neg_grid | Negative_grid | Number of points for negative   grid count Number of points for negative grid count, i.e. grid points outside   the ovary for the entire sample | Atresia_WGMEGS
Extra | Extra |   | Atresia_WGMEGS
YV_P | YolKVesicle_Profile | Number of Yolk Vesical cells   (point counts). | Atresia_WGMEGS
YV_YG_P | YolKVesicle_YolkGranule_Profile | Number of Yolk Vesical-Yolk   Granule cells (point counts). | Atresia_WGMEGS
YG_P | YolKGranule_Profile | Number of Yolk Granule cells   (point counts). | Atresia_WGMEGS
Oocyte_stage_1 | Previtellogenic oocytes | No white vacuoles   (cortical alveoli) visible. | Histological Screening
Oocyte_stage_2 | Early vitellogenic oocytes <400 um | Smallest vitellogenic   stage. White vacuoles visible. Yolk can be visible as well. Oocytes < 400   μm | Histological Screening
Oocyte_stage_3 | Vitellogenic oocytes | White vacuoles and yolk granules   visible. It is not necessary to     see vacuoles and granules at one time. Oocytes are between 400     and 800 μm. | Histological Screening
Oocyte_stage_4 | Migratory nucleus oocytes | Nucleus is migrating   from the middle of the oocyte towards the     side of the cell. The envelope of the nucleus breaks down, and     the nuclear contents blends with the surrounding cytoplasm. | Histological Screening
Hydration_state_1 | Early hydration | Yolk granules are   beginning to fuse together. Some     water has been taken up by the oocyte | Histological Screening
Hydration_state_2 | Advanced hydration | in the SISP-5 it is   refered as Mid hydrated….A large amount of water has been taken up by   the     oocyte. Interior and some cytoplasm still visible | Histological Screening
Hydration_state_3 | Late hydration | The oocyte is fully hydrated.   Yolk granules & cytoplasm     are no longer visible. The follicle layer is still attached. | Histological Screening
Egg_stage_1 | New eggs present | New eggs present | Histological Screening
Egg_stage_2 | Residual eggs present | Residual eggs present | Histological Screening
POFs | POFs | postovulatory follicle | Histological Screening
Spent | spent | A spent ovary is   characterised by the absence of normal vitellogenic oocytes at the end of   the     spawning period for that individual. Atretic vitellogenic oocytes and POFs   may be visible. | Histological Screening
MassiveAtresia | massive atresia | Massive atresia is   classed as when 90% or more of the vitellogenic oocytes in the ovary are   atretic.     In case of massive atresia, the fish will not spawn anymore that season. | Histological Screening
EarlyAlphaAtresia | early alpha atresia |   | Histological Screening
Discarded | Discarded | Discard sample for further   analyses - yes / no. For reasons other than in columns Oocyte Stage, Egg   Stage or Spent. If Yes, the Notes column will need to be filled. | Histological Screening
POF_stage_1 | Newly formed | different descriptions for horse   mackerel and mackerel | POF Staging
POF_stage_2 | Folded | different descriptions for horse   mackerel and mackerel | POF Staging
POF_stage_3 | Vacuolated | different descriptions for horse   mackerel and mackerel | POF Staging
POF_stage_4 | Compacted | different descriptions for horse   mackerel and mackerel | POF Staging
POF_stage_5 | Decreased sized | different descriptions for horse   mackerel and mackerel | POF Staging
POF_stage_6 | Advanced | different descriptions for horse   mackerel and mackerel | POF Staging
POF_stage_7 | Residual | different descriptions for horse   mackerel and mackerel | POF Staging



</body>

</html>

**Comment by evabrna** [comment]
Descriptions updated by Cindy (find the file here P:\DP1\projects\Fecundity&Atresia\Documents)

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/evab/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/evab/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Stage | Description | Detailed description | Scale
-- | -- | -- | --
YV | YolkVesicle | Number of Grid Points in the subsample using a Weibel grid which touch   Yolk Vesical cells. | Atresia_WGMEGS
YV_YG | YolkVesicle_YolkGranule | Number of Grid Points in the subsample using a Weibel grid which touch   Yolk Vesical-Yolk Granule cells. | Atresia_WGMEGS
YG | YolkGranule | Number of Grid Points in the subsample using a Weibel grid which touch   Yolk Granule cells. | Atresia_WGMEGS
Neg_grid | Negative_grid | Number of Grid Points in the subsample using a Weibel grid for negative   grid count, i.e. grid points outside the ovary wall. | Atresia_WGMEGS
Extra | Extra | Number of Grid Points in the subsample using a Weibel grid which are   extra, i.e. those touching empty areas within the ovary that occur due to   fixation of the sample. | Atresia_WGMEGS
YV_P | YolKVesicle_Profile | Total Number of Yolk Vesical cells (point counts) in the subsample. | Atresia_WGMEGS
YV_YG_P | YolKVesicle_YolkGranule_Profile | Total Number of Yolk Vesical-Yolk Granule cells (point counts) in the   subsample. | Atresia_WGMEGS
YG_P | YolKGranule_Profile | Total Number of Yolk Granule cells (point counts) in the subsample. | Atresia_WGMEGS
Oocyte_stage_1 | Previtellogenic oocytes | No yolk vesicles (white cortical alveoli) or yolk granules visible in the   oocyte. Diameter less than 180 μm. | Histological Screening
Oocyte_stage_2 | Early vitellogenic oocytes <400 um | Smallest vitellogenic stage, with oocytes < 400 μm. At this stage yolk   visecles (white cortical alveoli) are visible in the oocyte. Yolk granules   can be visible as well. | Histological Screening
Oocyte_stage_3 | Vitellogenic oocytes | Oocytes are between 400 and 800 μm in diameter. At this stage yolk   vesicles (white cortical alveoli) and yolk granules are visible in the   oocyte. | Histological Screening
Oocyte_stage_4 | Migratory nucleus oocytes | In this stage the nucleus is migrating from the middle of the oocyte   towards the periphery of the cell. Lipids start to concentrate and will fuse   into one drop. Stage ends when yolk granules start to fuse and hydrate. | Histological Screening
Hydration_state_1 | Early hydration | The yolk granules in the oocyte are beginning to fuse together anf   hydrate. | Histological Screening
Hydration_state_2 | Advanced hydration | The majority of the yolk granules have fused and hydrated to larger   sizes. | Histological Screening
Hydration_state_3 | Late hydration | The oocyte is fully hydrated and only one big yolk vacuole is present.   Yolk granules & cytoplasm are no longer visible. The follicle layer is   still attached. | Histological Screening
Egg_stage_1 | New eggs present | Complete fusion and hydration of the oocyte and the follicle layer has   disappeared. | Histological Screening
Egg_stage_2 | Residual eggs present | Hyaline eggs that remain in the ovary after a batch is spawned. These   eggs show signs of degradation and/or resorption. | Histological Screening
POFs | POFs | One or more Postovulatory Follicle(s) present in the ovary. | Histological Screening
Spent | spent | A spent ovary is characterised by the absence of healthy vitellogenic   oocytes at the end of the spawning period for that individual. Atretic   vitellogenic oocytes and POFs are present and residual eggs may be visible. | Histological Screening
MassiveAtresia | massive atresia | Massive atresia is classed as when 90% or more of the vitellogenic   oocytes in the ovary are atretic. In case of massive atresia, the fish will   not spawn anymore that season. | Histological Screening
EarlyAlphaAtresia | early alpha atresia | Alpha atresia begins when there is a cut through one or both chorion   layers. The break is smaller than twice the width of the chorion thickness in   any of the two chorion layers. The edge of the oocyte is smooth. | Histological Screening
Discarded | Discarded | Discard sample for further analyses - yes / no. For reasons other than in   columns Oocyte Stage, Egg Stage or Spent. If Yes, the Notes column will need   to be filled. | Histological Screening
POF_stage_1 | Newly formed | Large POF and cordlike structure well defined. | POF Staging
POF_stage_2 | Folded | POF with line structure but with evident loops. | POF Staging
POF_stage_3 | Vacuolated | POFs still large, with folds clearly recognisable. | POF Staging
POF_stage_4 | Compacted | POFs still large but compact. Folds barely distinguishable. | POF Staging
POF_stage_5 | Decreased sized | POFs compact and folds indiscernable. | POF Staging
POF_stage_6 | Advanced | POFs size reduced strongly and seem a mass of disordered cells and   vacuoles. | POF Staging
POF_stage_7 | Residual | Very small POFs and scarce. | POF Staging



</body>

</html>

**Comment by MariaMakri** [comment]
To check if the description changes are implemented.
