### ISSUE TITLE
Dataset Naming - Seabirds

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-eg/DIG#250]
We have:

Biodiversity: Sea birds
European Seabirds at Sea

Suggest to rename:

Biodiversity: Seabirds - nesting and breeding
Biodiversity: Seabirds at sea

**Comment by Osanna123** [comment]
We can consider changing the dataset labels for birds, especially adding the 'Biodiversity:' part.
However, the suggested names are not ok, because:
1. the https://datsu.ices.dk/web/selRep.aspx?Dataset=124 is for the Abundance (for both breeding and non-breeding data) and Breeding success Indicators
2. https://datsu.ices.dk/web/rptChk.aspx?Dataset=148 present name is inherited from 'ESAS', and is for the 'raw' observations at sea.

**Comment by neil-ices-dk** [comment]
> 
> 
> We can consider changing the dataset labels for birds, especially adding the 'Biodiversity:' part. However, the suggested names are not ok, because:
> 
>     1. the https://datsu.ices.dk/web/selRep.aspx?Dataset=124 is for the Abundance (for both breeding and non-breeding data) and Breeding success Indicators
> 
>     2. https://datsu.ices.dk/web/rptChk.aspx?Dataset=148 present name is inherited from 'ESAS', and is for the 'raw' observations at sea.

thanks Anna - so what is the solution, just to add Biodiversity as a prefix?

**Comment by cekv** [comment]
Biodiversity: European Seabirds at Sea
Biodiversity: Seabirds (Ospar needs to confirm ANY name changes)

**Comment by neil-ices-dk** [comment]
> Biodiversity: Seabirds (Ospar needs to confirm ANY name changes)
as soon as accepts the invite to DIG repo (ospar-odims) we can tag him ;)

**Comment by odontaster** [comment]
Hi @moultonc would you have a look at this issue and give us your feedback? thanks

**Comment by pcrjoana** [comment]
Do we have any news on this?

**Comment by Osanna123** [comment]
dataset/ver names are edited
