### ISSUE TITLE
new MPROG MSFD-D8

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#35]
New code for MPROG MSFD-D8

ID | NA
-- | --
Start time | 01/13/21
Email | Anonymous
Name |  
Requested by | Env.data submitter
Request entered by | Anna Osypchuk
Requester email | mario.milhomens@ipma.pt
vocabulary type change | Code value (new);
vocabulary reference | https://vocab.ices.dk/?ref=147
Reason for change | To mark data submissions with the respective program reference
Impact of change | Low
Does the proposed change exist in another ICES vocabulary code type or an external code standard | No
If yes, please specify |  
Proposed time when the change should take affect from  |  asap, 01/15/2021

**Comment by neil-ices-dk** [comment]
ok, i'm going to quietly ignore the fact that the MSFD is not a monitoring programme but a framework (Article 11 is the monitoring programme, and that is really referring to other monitoring programmes as there are no monitoring programmes devised under the MSFD - although a Member State may make a national programme and call it an MSFD Descriptor monitoring programme).

so i would suggest seeing as you already have some of the Decsriptors in, that you put the whole list so we can refer to it in its completeness, rather than fragments.

**Comment by Osanna123** [comment]
Need

**Comment by Osanna123** [comment]
Need a respective term in PRGOV as well: 
https://vocab.ices.dk/?ref=1473

**Comment by pcrjoana** [comment]
We suggest adding MSFD descriptors to PRGOV as needed. It's OK to add MSFD-8. :-)
