### ISSUE TITLE
Adding challenges and opportunities tracker to Github

### ISSUE THREAD

**Issue by sjurl** [ices-eg/DIG#375]
Create separate organization level project for challenges and opportunities
* Add all information from sharepoint
* share with governance groups

Create review plan for the challenge and opportunity
* categorize
* review
* accept/reject
* timeline for review

**Comment by neil-ices-dk** [comment]
@sjurl i have started this and want you to take a look and see if you think this will work before i put all the entries across:

list view https://github.com/orgs/ices-eg/projects/6/views/1
board view https://github.com/orgs/ices-eg/projects/6/views/2

the project board is now linked to the DIG projects (note that the new project type sits at the ICES-EG organization level, rather than within the DIG repository

![image](https://user-images.githubusercontent.com/23527005/197485274-447e2b7a-2e01-4bb4-9504-769f6c6f092c.png)

**Comment by sjurl** [comment]
Everything moved from sharepoint to github https://github.com/orgs/ices-eg/projects/6/views/1
