### ISSUE TITLE
Deprecate CodeType EL_Survey

### ISSUE THREAD

**Issue by evabrna** [ices-eg/DIG#427]

**Comment by cekv** [comment]
@odontaster to begin the process to check EL_survey, AC_survey, and others. 
@evabrna and @pcrjoana to check smartdots and fecundity and atresia.

**Comment by evabrna** [comment]
we decided to use Survey for fecundity and atresia. So, EL_Survey is not being used

**Comment by odontaster** [comment]
Implemented

**Comment by odontaster** [comment]
Reverted because there is no one to one match between EL_survey and Survey. This causes changes in the submission and in the data browsing. As the governance group is about to start, we think this might be a good first issue for them. We do expect this change will be implemented, we just need the groups involvement to review what this entitles for the resubmissions.

**Comment by odontaster** [comment]
RHLS: deprecate the existing ones and create a new one with no quarter indication, link them.

**Comment by odontaster** [comment]
need to create 3 new Survey codes for historical datasets in ELDB:
- Gulf of Riga Larvae survey (there are 3 surveys but none mentions larvae)
- North sea cod and plaice egg surveys
- Atlantic Anguilla surveys

**Comment by MariaMakri** [comment]
@odontaster check the sheet with survey codes to see if the surveys already exist or add them if not.
@cekv to share the link.
