### ISSUE TITLE
GearType: add LHP

### ISSUE THREAD

**Issue by odontaster** [ices-eg/DIG#507]
Add LHP to https://vocab.ices.dk/?codetypeguid=6f65b819-57ca-4904-a961-2d55699008d5

What is the difference between that one and this one:
https://vocab.ices.dk/?codetypeguid=49285fce-fb68-4596-81a4-b91ca52ad6ec
We need to improve description of codeType.
In RDBES they call it FAO Gear Type. Why not use Gear Type as in FDI? is that the other one?

**Comment by odontaster** [comment]
[2023_FDI_codes (4).xlsx](https://github.com/ices-eg/DIG/files/12573889/2023_FDI_codes.4.xlsx)

**Comment by MariaMakri** [comment]
Complete gear Type to equal gear type L4 
Work on deprecating gear type
Suggest improvements for external code type descriptions on metiers

**Comment by odontaster** [comment]
Added link to RCGs master files for Metier Level6 and Level4. Pending best link for Level 3 and Level 5.

**Comment by odontaster** [comment]
@MariaMakri to work in the RDBES team to move towards the common CodeTypes.

**Comment by MariaMakri** [comment]
GearType will be deprecated by february 2024 and GearTypeL4 should be used.

**Comment by cekv** [comment]
@HenrikK-N to discuss with @cmspinto regarding what would include to change codetypes between databases

**Comment by MariaMakri** [comment]
@HenrikK-N to confirm results from conversation with @cmspinto regarding the two code types, so we can move on with deprecating GearType. 
Otherwise GearType will be deprecated by the end of May.

**Comment by HenrikK-N** [comment]
Dear @MariaMakri , @odontaster, @cekv, @cmspinto, @colinpmillar, @neilcampbelll.

It make sense to deprecate one of the identical code types for gear type: ‘GearType’ or ‘GearTypeL4’.
The question is, which one should it be? What makes sense? Which change carries the least work? That is what I wanted to find out by talking with Carlos. It does not make sense just to decide on deprecating one code type, without looking in the consequences and the work needed to be implemented for the deprecation. The following is the reasoning for the agreement. In the RDBES the ids of the codes are stored in the database as a reference to the codes, which is best practise, then a typo in a code or an agreed change, only need to be updated in the reference system. If it is decided to deprecate the ‘GearType’, then we would have to change the import and export module source code for 3 tables, where we find the ids for the codes. We will also make changes in the source code for the 3 tables in the checking part of the codes. We will also have to update id for more than 250.000 Sample records and more than 100.000 Fishing operation records, and about 20.000 Landing event records. Finally the data model reference would have to be updated for 3 tables. Now the question was how many fields and source code places need to be updated in the Bycatch and VMS (Carlos said VME is not using gear type, that also matches that in RECO only Bycatch and VMS are linked to ‘GearTypeL4’). The Bycatch and VMS stores the codes directly in the DB, so there are no id look up in ‘GearTypeL4’. Since the codes of the two gear type code lists they are the same, the change would only be to update the reference in the format to ‘GearType’ for the Bycatch and the VMS format, and in the import script check (I talked with Colin and Neil C, this is very easy change - just deleting the ‘L4’ in one place in the check script). Therefore Carlos agreed it made sense to keep the ‘GearType’, and deprecate the ‘GearTypeL4’, so that is now agreed. 
Since Neil C. right now is working on a data call for the VMS, he needs to know during this week, if he should make the update now or after the data call. I suggest to do it now, I can talk with Neil C. If someone object to make the change now this week, please speak up now? 
Cheers : )

**Comment by Osanna123** [comment]
Change description in GearType to the one from GearTypeL4.
Re-map related codes from VMS, Bycatch, and inform the GGs on the change, which will affect users' scripts.
Deprecate GearTypeL4

**Comment by pcrjoana** [comment]
GearType implemented in VMS, and CodeType description updated.

**Comment by odontaster** [comment]
GearType implemented in Bycatch. GearTypeL4 codes have been deprecated, and CodeType made invisible. A comment on the long description added with a link to this issue.

**Comment by odontaster** [comment]
Added links between GearType and GearGroup, 
https://github.com/orgs/ices-eg/projects/19/views/1?pane=issue&itemId=100265585&issue=ices-eg%7CDIG%7C750
