### ISSUE TITLE
RMG to review and comment in this document:

### ISSUE THREAD

**Issue by MariaMakri** [ices-eg/DIG#509]
https://community.ices.dk/Committees/DIG/DIG%202022/04.%20Working%20documents/Subgroup_Reference_Management_Best_Practices

https://github.com/ices-eg/DIG/projects/1#card-78140338

**Comment by pcrjoana** [comment]
Direct link to document: https://community.ices.dk/Committees/DIG/DIG%202022/04.%20Working%20documents/Subgroup_Reference_Management_Best_Practices/ICES%20guidelines%20for%20reference%20requests.docx

**Comment by MariaMakri** [comment]
Review by next RMG

**Comment by neil-ices-dk** [comment]
### Looks good, some general comments:

- we are missing a 'why' as in why do we bother with all these codes in the first place
- as this will become an ICES publication, need to ensure simplicity and consistency i.e. suggest 'Glossary of terms' for all concepts rather than two sub-lists of terms
- i think we should refer to a data management best practice i.e. IODE that outlines that master code reference management is an important aspect of data best practices

**Comment by odontaster** [comment]
https://community.ices.dk/Committees/DIG/DIG%202022/04.%20Working%20documents/Subgroup_Reference_Management_Best_Practices/ICES%20guidelines%20for%20reference%20requests_nov23.docx

Hi @pcrjoana it would be great if you could have a look to the document. Thanks

**Comment by odontaster** [comment]
Hi @neil-ices-dk. Wold you have a link to the IODE document? I have been searching for it but can't find it. Thanks.
Apart from that comment, the document would be ready for you to review, if you can find the time. Let me know anytime and thanks.

**Comment by odontaster** [comment]
Received feedback from @HenrikK-N . A few good points and a critical change.
