### ISSUE TITLE
RDBES: New and updates of codes for DifferenceReason

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#562]
Now when countries are starting to use the codes for DifferenceReason in the RDBES. The Core Group found out that codes was missing and other codes should be updated for the code type: DifferenceReason, please see below:

Updates:
Update: code 'Areamis' to 'Area' and the description from 'Area misreporting' to 'Area correction'. (To move away from the ‘hard’ word ‘misreported’)
Update code 'Corrowb' to 'Overwbox'. (To make more intuitive)
Update code ‘NoDiff’ to ‘NoDiffAssumed’ and description to ‘No difference assumed’ (to differentiate from the new needed code ‘NoDiffKnown’)
Update description on ‘Unallocc’ ‘Unallocated catches’ to ‘Unallocated or additional weights that cannot be allocated to specific trips or vessels.’ (To explain better what is is)

The following new codes should be added:
Code          Description
'Metier'      'Estimated metier, based on logbook information or estimated (which is the case of SSF in some cases)
'Other'       'Other corrections'
'Multiple'   ‘Multiple corrections, e.g., in case there is both an area correction and a scientific metier estimation’
‘Species’	  ‘Species correction’ 
‘NoDiffKnown’  ‘No difference known’
‘NoOfficial’ ‘No official data available’

**Comment by MariaMakri** [comment]
Sample data” if sampling data are used to correct the official weights, “Unallocated catches” if there is knowledge about unallocated catches, “Area misreporting” if e.g. VMS data indicates fishing in another area than officially reported or “Correction for overweight in boxes” if sampling data indicates overweight in boxes.

**Comment by MariaMakri** [comment]
The code is just a label it has no intrinsic meaning.  RDBES is now a production system and we should, therefore, minimise unnecessary changes.
RMG recommend that the code Areamis is kept as is and the description changes to 'Area correction'.
'Corrowb' code label remains as is.
'NoDiff' code label remains the same, the description updated to suggestion.
Update description on ‘Unallocc’ ‘Unallocated catches’ to ‘Unallocated or additional weights that cannot be allocated to specific trips or vessels.’

The following new codes should be added:
Code Description
'Metier' 'Estimated metier, based on logbook information or estimated (which is the case of SSF in some cases)
'Multiple' ‘Multiple corrections, e.g., in case there is both an area correction and a scientific metier estimation’
‘Species’ ‘Species correction’
‘NoDiffKnown’ ‘No difference known’
‘NoOfficial’ ‘No official data available’

Regarding the code 'Other'  with description 'Other corrections', there is no description provided of what other corrections are included. It is preferred to add new codes as needed rather than having an 'others' code. Having specific codes facilitates data analysis.

**Comment by odontaster** [comment]
@HenrikK-N for your review before tomorrow meeting.

**Comment by cekv** [comment]
RMG  agrees to change codes as a one-time exception. 
@HenrikK-N to check with core group regarding the code "Other" - if there is a limited list of suggestions or QC'ed for new codes (warning during submission).

**Comment by MariaMakri** [comment]
The following updates were implemented:
Updated code 'Areamis' to 'Area' and the description from 'Area misreporting' to 'Area correction'
Updated code 'Corrowb' to 'Overwbox'.
Updated code ‘NoDiff’ to ‘NoDiffAssumed’ and description to ‘No difference assumed’
Updated description on ‘Unallocc’ ‘Unallocated catches’ to ‘Unallocated or additional weights that cannot be allocated to specific trips or vessels.’ 

The following new codes were added:
Code Description
'Metier' 'Estimated metier, based on logbook information or estimated 
'Other' 'Other corrections'
'Multiple' ‘Multiple corrections, e.g., in case there is both an area correction and a scientific metier estimation’
‘Species’ ‘Species correction’
‘NoDiffKnown’ ‘No difference known’
‘NoOfficial’ ‘No official data available’
