### ISSUE TITLE
RDBES: New code BioStructAgeNotRead for codetype BiologicalMeasurementType

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#569]
The RCGs would need to record biological structures collected for age data but not read in the RDBES, typically otoliths.
The Core Group agreed that the best solution would be to add a new code to the codetype BiologicalMeasurementType:

Code     	                     Description
BioStructAgeNotRead   Biological structures collected for age data but not read

It is hope that this request could be discussed at your meeting Tuesday 16 January and hopefully 
with an approval. Because it would be best to have an approval before the RCG and ICES data call is send next week.

**Comment by cekv** [comment]
AgeOtolithNotRead and AgeScaleNotRead are to be created instead of the generic code suggested.

**Comment by MariaMakri** [comment]
On today's RDBES core group meeting, it was discussed to change this requested code to two codes, one for otoliths and one for scales: 

OtolithCollected
Description: Indication on otolith collected and potentially archived. To be used for all collected otoliths including when an age is provided.

ScaleCollected 
Description: Indication on scale collected and potentially archived. To be used for all collected scales including when an age is provided.

The rationale behind this, is that biological structures are usually collected but not read, and in some cases archived. There is another field to indicate whether the otoliths were unreadable, so this code should only provide the information that the otolith has been collected. 

The word 'indication' on the description seems vague, but it was agreed upon, since in some cases there might be reasons such as accidents, where the otolith was removed but could not be saved, and the group decided that a mere indication of collected otoliths is enough.

**Comment by odontaster** [comment]
@MariaMakri Core group request seems quite in line with what RMG reccomended.
@cekv @Osanna123 @pcrjoana @neil-ices-dk please react to this, as these codes are needed for upcoming data call. Thanks!

**Comment by cekv** [comment]
@MariaMakri I also think this is in line with what we discussed

**Comment by MariaMakri** [comment]
The two codes have been added in RECO.
