### ISSUE TITLE
RDBES: New code Population added to code type BiologicalMeasurementType 

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#602]
Hi, the Core Group request the following new code added to code type BiologicalMeasurementType:

Code             Description
Population     Indication of a group of fish of one species, which shares common ecological and genetic features. Use for populations (biological units) for specific species e.g. herring populations defined by WKSIDAC2.

The definition i from the ICES Glossary: [https://www.ices.dk/lists/glossary/ices%20glossary.aspx#InplviewHashe4199c10-9657-46b2-bf8b-e7de42ff06a6](url).
Cheers

**Comment by odontaster** [comment]
Hi @HenrikK-N this issue has been around for a while now
https://github.com/ices-eg/DIG/issues/478

It has been agreed also with ACOM leadership approval to create the GeneticPopulation Code type, with codes like Her-001, Her-002, Her-003 etc and descriptions as the ones in the WKSIDAC2 report. 
The codes functioning will be similar to ICES_StockCodes regarding splits and merges, deprecating the old ones so they can't be used.
Hope this looks fine also for RDBES, let us know otherwise, as it would definitely be good to use the same CodeType for this upcoming feature.

**Comment by MariaMakri** [comment]
@HenrikK-N to confirm that the code should be 'GeneticPopulation' instead of Population 
@MariaMakri to create the code
