### ISSUE TITLE
RDBES: New code ‘IlliciaCollected’ in codetype 'BiologicalMeasurementType'  

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#624]
Hi, can the following new code be added in codetype 'BiologicalMeasurementType':
Code                       Description
‘IlliciaCollected’       Indication on illicia collected and potentially archived. To be used for all collected illicia including when an age is provided.

**Comment by MariaMakri** [comment]
Ilicia are used in many cases instead of otoliths for age estimation: 

https://www.sciencedirect.com/science/article/pii/S0272771421004078


The occurrence of secondary structures makes age estimation using otoliths difficult ([Crozier, 1989] As a consequence, the [illicium](the modified first spine of the dorsal fin, which acts as a lure) is the preferred structure for routine age estimation in most European countries ([ICES, 2011 [Landa et al., 2008]. The periodicity of growth marks in illicia has been indirectly validated using length [cohort analysis.

**Comment by Osanna123** [comment]
To be consistent with the other codes, @MariaMakri please create code IlliciumCollected

**Comment by MariaMakri** [comment]
Code IlliciumCollected has been created
