### ISSUE TITLE
review of descriptions of roles codetype

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-eg/DIG#646]
Hi Ladies,

In DIG we were discussing the data policy and that led to looking at some of the other docs. Can we take a look at the existing vocab for **roles** and align with the data management handbook.

https://vocab.ices.dk/?codetypeguid=82ad7124-5482-4319-8870-bc97293dafca 

ICES (2024). Best Practices for Data Management. ICES User Handbooks. Report. https://doi.org/10.17895/ices.pub.25435903.v1

**Comment by pcrjoana** [comment]
From the data management handbook:

Custodian: the person or organization that maintains and ensures access to the data.
Originator: the person or organization that acquired the data. Custodians and originators
are often the same, but not always.
Publisher: the person or organization that publishes the data.
Distributor: the person or organisation that distributes the data.
Owner: The person or organization that owns the data.

**Comment by pcrjoana** [comment]
To align the vocab with the data management handbook, we would have to add "publisher" and "distributer" as codes, as well as change the description of custodian, originator and owner.

I suggest we also change the description of the code type to have "person or organization" instead of "party", and to reference the handbook in the description as well.

**Comment by neil-ices-dk** [comment]
i would perhaps suggest we start with the codes in use (align descriptions) and hold off on adding the additional codes as no one has requested them.
