### ISSUE TITLE
New stock codes for horse mackerel

### ISSUE THREAD

**Issue by Milldaz** [ices-eg/DIG#653]
Division 4.a used to be 'shared' between the NS and W stock (two quarters of the year in each) and Division 3.a used to be in the NS stock. Now both 3.a and 4.a are in the western stock only. This requires two stock codes to change slightly:

North Sea Horse Mackerel (Old Stock Code: hom.27.3a4bc7d)
New Stock Code: 
hom.27.4bc7d
New Description:  
Horse mackerel (Trachurus trachurus) in divisions 4.b, 4.c, and 7.d (southern and central North Sea, eastern English Channel)

Western Horse Mackerel (Old Stock Code: hom.27.2a4a5b6a7a-ce-k8)
New Stock Code: 
hom.27.2a3a4a5b6a7a-ce-k8
New Description: 
Horse mackerel (Trachurus trachurus) in Subarea 8 and divisions 2.a, 3.a, 4.a, 5.a, 6.a, 7.a–c, and 7.e–k (Northeast Atlantic and adjacent waters)

**Comment by odontaster** [comment]
Good to go, descriptions have been reviewed by editorial office.
Need to be created also in IC_Stock, and inform Henrik, as they will be used.

**Comment by odontaster** [comment]
@odontaster  to create both codes in ICES_StockCode and IC_Stock. Link to year 2024, inform Henrik and Maria for IC.

**Comment by HenrikK-N** [comment]
Hi Adriana and David.
I just checked the stock definition in InterCatch and there I could see for the new stock hom.27.2a3a4a5b6a7a-ce-k8 it was set up to area 5a, as written in the definition above (2.a, 3.a, 4.a, 5.a, 6.a, 7.a–c, and 7.e–k). But the stock code says '...5b...' and the old stock's name was also with '...5b...' and the area 5b was set up for the old stock, so I guess area 5b should be linked to the new stock instead of area 5a : )

**Comment by odontaster** [comment]
Dear @HenrikK-N 
That is a good catch, thanks. I did modify all descriptions for 
hom.27.2a3a4a5b6a7a-ce-k8
with
Horse mackerel (Trachurus trachurus) in Subarea 8 and divisions 2.a, 3.a, 4.a, 5.**b**, 6.a, 7.a–c, and 7.e–k (Northeast Atlantic and adjacent waters)

**Comment by MariaMakri** [comment]
Hi @HenrikK-N 
You are right, I could see that the stock was linked to Divisions only, I have now linked it to all the above areas. 

Cheers, 

Maria
