### ISSUE TITLE
RDBES: Remove spaces in the all the codes for RS_MeasurementType

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#87]
Remove spaces in the all the codes for RS_MeasurementType.
E.g: 
Code
Fork Length

Updated to:
ForkLength

etc.

**Comment by pcrjoana** [comment]
@cekv to discuss this with the RDBES core group. This (https://vocab.ices.dk/?ref=1644) seems to be a duplicate of another RDB vocabulary http://vocab.ices.dk/?ref=1606, and also of https://vocab.ices.dk/?ref=1395 and https://vocab.ices.dk/?ref=1392.

**Comment by davidcurrie2001** [comment]
These aren't duplicates but are close in topic.  The issue is that in the table ("FM") where RS_MeasurementType is used not all of the values in RS_BiologicalMeasurementType will be allowed e.g. it doesn't make sense to allow people to use the value 'Sex' from RS_BiologicalMeasurementType in the "FM" table which stores data relating to length or weight measurements.  The values in TS_LenMeasType only refer to length measurements, but we also need to allow weight measurements in the FM table - perhaps this list can be excpanded to include weight measurments? (I'm not sure why you have referred to the TS_OtGrading list which doesn't have anything to do with weight or length measurements).

**Comment by davidcurrie2001** [comment]
Is there any way of deriving a new ICES code list from selected values of other code list(s)?  E.g. we could define a code list for a field in the “FM” table in the RDBES that contained a sub-set of values from other code list (s) - see attached
[derivedCodeListExample.xlsx](https://github.com/ices-eg/DIG/files/6575897/derivedCodeListExample.xlsx)

**Comment by cekv** [comment]
Recommend to drop RS_ - also to combine the codes into one and map the respective records.

**Comment by cekv** [comment]
Removed the spaces before data call, but this topic is far from closed
