### ISSUE TITLE
New code type RS_CertaintyQualitative

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#92]
A new code type RS_CertaintyQualitative needs to be created for the RDBES. The following are the codes and descriptions:

Code	Description
AQ1	Rings can be counted with certainty. Quality measurement associated with age.   
AQ2	Rings can be counted, but with difficulty and some doubt. Quality measurement associated with age.   
AQ3	Rings can not be counted, the calcified structure is considered unreadable (no age assigned). Quality measurement associated with age.
AQ4	Rings can not be counted, the calcified structure is considered unreadable, age assigned for QA purposes only. Quality measurement associated with age.   
Unknown	When not recorded.
NotApplicable	When no qualitative measurement exists for the Biological variable type. E.g. length.

**Comment by pcrjoana** [comment]
There is a vocabulary with the same concept already: https://vocab.ices.dk/?ref=1395
We propose removing the "TS" prefix from the existing vocab, updating the description under "NA" and adding a code for "Unknown".
A discussion is needed with @vaishav before a decision can be made.

**Comment by davidcurrie2001** [comment]
I agree there's no point duplicating existing codes but the plan with this code list is to expand it in the future to include similar quality descriptions for other biological measurements e.g. lengths, weights.  These other codes don't exist yet but a group such as WGCATCH should be involved in creating them.  Given the direction we want to head in what's the best way to proceed?

**Comment by pcrjoana** [comment]
From @JCoadDavies:

> The newly proposed code would change the AQ3_QA to AQ4. I think this would confuse readers in some way as they are now familiar with the AQ3_QA and think it may be best left as AQ3_QA
> 

This is a reference to the AQ codes being used in SmartDots. The proposed AQ4 code already exists in SmartDots as AQ3_QA, and it's Julie's opinion that it should be kept as AQ3_QA, due to the implications for SmartDots.
She also mentioned that even though the AQ codes are currently specific for assessing the quality of age readings, they could potentially be used universally across SmartDots.

**Comment by cekv** [comment]
@AnnelieH, please read the thread above and provide an opinion if AQ-codes should be universal for all biological measurements or specific for each type of biological measurement?

**Comment by davidcurrie2001** [comment]
Ok, I agree we should use AQ3_QA rather than AQ4 if we want to be consistent with SmartDots.  If the AQ codes are made more generic then there will need to be more specific examples about they should apply to other types of measurements such as length, maturity, any other measured parameters.

**Comment by HenrikK-N** [comment]
@cekv I cannot find the codes used for SmartDots, can you send a link to them. We of course need to be consistent with the most up-to-date codes. But if the RS_CertaintyQualitative is in sync with TS_OtGrading https://vocab.ices.dk/?ref=1395 and not with SmartDots, the TS_OtGrading is also not is sync with SmartDots and then we should not remove the 'TS_' in TS_OtGrading and use that.

**Comment by cekv** [comment]
[ProcessForManagementOfChangesToReferenceData_loes.docx](https://github.com/ices-eg/DIG/files/6614504/ProcessForManagementOfChangesToReferenceData_loes.docx)

**Comment by AnnelieH** [comment]
WGBIOP thinks that we should keep AQ3_QA instead of changing to AQ4. We also think that the codes can be used for other parameters but the description might need to be changed. For example rings can't be used for maturity then stage can be used in stead. Or a more generic description has to be made that can be applied for all.

**Comment by vaishav** [comment]
I vote for one generic code type if the definition follows across the databases, for DATRAS we have no issue if you want to refer to this code without TS_ as a prefix, only the condition is that the interpretation of the code and the code name need to be the same as it is defined in the TS_OtGrading, in short TS_OtGrding codes need to be a subset of the full list of code. As far as RECO concern I do not see there is an issue if the prefix changes because triggers will act accordingly in SQL, unless if it is hardcoded somewhere and it needs to change accordingly.

**Comment by cekv** [comment]
Name change to MeasurementCertainty and follow SmartDots definitions - reuse TS_Otgrading
