### ISSUE TITLE
WKDSG recommendation on guidance and guidelines

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-eg/DIG#94]
discussed to be led by DIG (Sjur, Ingeborg and Neil) with WGQUALITY and DSTSG chairs also involved;

**Comment by sjurl** [comment]
@sjurl to call for a meeting on this

**Comment by davidcurrie2001** [comment]
As a reminder here is the recommendation from WKDSG: 
"_WKDSG recommends that resources are developed for assisting data-collectors in identifying standards their data-collection need to adhere to. WKDSG suggest that this can be implemented as a publicly available online ‘portal’ that utilises existing docu-ment repositories and the WKDSG resource inventory. It should include a guidance document whose purpose is to assist the process of identifying which standards are relevant for a particular data-collection activity. It will be important in this respect that the document explains the principles for data acceptance, and that it explains the da-ta-flow pathways so that data-providers are able to identify which data-users to coor-dinate with._"

**Comment by sjurl** [comment]
@sjurl set up a doodle for a meeting to progress this work - mid march

**Comment by sjurl** [comment]
Set up doodle to progress task: https://doodle.com/meeting/participate/id/e7LRN38a

**Comment by neil-ices-dk** [comment]
@sjurl this was discussed in WGQUALITY (Jan 2022) and they would like to hear if there is going to be any progress on this in DIG in 2023?

**Comment by neil-ices-dk** [comment]
@sjurl to look to have a short meeting before DIG to follow-up (potentially 8th May?)

**Comment by sjurl** [comment]
Way forward

Update data management handbook 
- to reflect /make it easier to identify how to contribute data to ICES (nice graphics)
- Who to talk to / contact your WG etc
- Look at annex 6 from WKDSG
- Consideration for next update of Data Management Handbook to include this.

Linking to good documentation on data collection guidelines and standards

- Create a collection within the ICES library or with tags
   - Focused on guidlines and standards used for data collection
   - Both ICES and non ICES  guidelines and standards
   - Introduce tag in ICES figshare and get people to use it

- Take it up with OBPS - week of DIG
  - possibility to create virtual collections within OBPS?
    - maintainable by external (i.e. ICES)?
    - Link to other publications outside ICES?

Who has Science / Industry collaboration as a focus 
- can't see a specific working group that has this as their main focus
- Possible reccomendation from DIG 2023
- Relevant workshop https://www.ices.dk/community/groups/Pages/WKEMSIP.aspx

**Comment by neil-ices-dk** [comment]
> Create a collection within the ICES library or with tags

@sjurl @jensr @davidcurrie2001 

Spoke with Ruth and this is indeed possible, and already it is possible to add publications that are created/hosted elsewhere; it may be that we are limited to using keywords rather than tags, but this is something that is achievable now. We just need to consider maintenance....

https://ices-library.figshare.com/external-pubs/groups

![image](https://github.com/ices-eg/DIG/assets/23527005/38c26f06-41c5-4ebd-83fd-bbb46b29c474)

-----

![image](https://github.com/ices-eg/DIG/assets/23527005/f69f4dc7-9232-42ac-95fd-f9f4695f514d)

**Comment by sjurl** [comment]
Taken forward as signposting of guidelines https://github.com/ices-eg/DIG/issues/457
